### PR TITLE
mem: set_len should update inode length

### PR DESCRIPTION
**Pull request by hpingfs**
set_len should update inode length

### CODE REVIEW

**Comment by hpingfs** [comment]
@twmb Could you help take a review for this PR?

**Comment by twmb** [comment]
@hpingfs this lgtm,
how much are you actively using this project? I think it's probably due for some updates since my last main work on it was 5yr ago. I'm happy to merge this, but lmk if you have some more ideas on future maintenance :)

I'll also need to look up how to release a rust crate again 😅

**Comment by hpingfs** [comment]
@twmb Thanks for the quick review. It will be really helpful to me to have the new crate with this fix released.

I'm currently using rsfs as a in-memory fs to do a quick verification in my project. I'm interested in the error injection as well, and may have some more contribution in future.

According to the docs: https://docs.rs/rsfs/latest/rsfs/

> In the future, an error-injectable shim around the in-memory file system will be provided 
> to help trigger filesystem errors in unit tests.

How about the status of the error injection support? It looks to me an  injector has already been implemented in the mem/test/unix.rs, do you plan to refine this implementation?

**Comment by twmb** [comment]
As mentioned, I haven't touched this in 5yr. I haven't done anything related to error injections. If you'd like to maintain this project, lmk.

**Pull request merged**
